# Generated by Django 3.2.6 on 2021-08-22 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210820_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('tableId', models.AutoField(primary_key=True, serialize=False)),
                ('tableNumber', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=False)),
                ('isNotify', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
