# Generated by Django 3.2.6 on 2021-08-26 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsImage',
            fields=[
                ('catImgId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemImg', to='api.items')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userimgitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
