# Generated by Django 3.2.6 on 2021-08-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_itemsimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsimage',
            old_name='catImgId',
            new_name='itemImgId',
        ),
    ]
