# Generated by Django 3.2.6 on 2021-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_catimgid_itemsimage_itemimgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='chair',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
