# Generated by Django 3.2.6 on 2021-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tables_chair'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEst',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
