# Generated by Django 3.2.6 on 2021-08-26 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_typeest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableImage',
            fields=[
                ('tableImgId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tables')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableImg', to='api.items')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userimgtable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
