# Generated by Django 3.2.6 on 2021-08-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tableimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableimage',
            name='items',
        ),
        migrations.AddField(
            model_name='tableimage',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableImg', to='api.tables'),
        ),
    ]
